# Generated by Django 4.2.6 on 2023-12-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0002_alter_payment_borrowing_alter_payment_money_to_pay_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=500),
        ),
    ]
